"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var alumnos_1 = require("./alumnos");
var profesores_1 = require("./profesores");
var escuela_1 = require("./escuela");
var alumno1 = new alumnos_1.Alumno("Diana", "Ciganda", 41, 9, 2);
var alumno2 = new alumnos_1.Alumno("Pamela", "Tolosa", 38, 8, 4);
var alumno3 = new alumnos_1.Alumno("Juan", "Rodriguez", 35, 6, 8);
var alumno4 = new alumnos_1.Alumno("Jazmin", "Lopez", 30, 4, 10);
var alumnos = [alumno1, alumno2, alumno3];
var profesor1 = new profesores_1.Profesor("Karen", "Simari", "Programacion", alumnos, 7);
var profesor2 = new profesores_1.Profesor("Braian", "Aued", "Programacion II", alumnos, 1);
var profesor3 = new profesores_1.Profesor("Viviana", "Blasco", "FIP", alumnos, 8);
var profesor4 = new profesores_1.Profesor("Nelson", "Garrido", "Tutoria", alumnos, 2);
var profesores = [profesor1, profesor2, profesor3];
var escuela = new escuela_1.Escuela(alumnos, profesores);
//Matricular un nuevo alumno
escuela.setMatricularAlumno([alumno4]);
console.log("----------------------------------");
escuela.setMatricularAlumno([alumno1]);
console.log("----------------------------------");
console.log(alumno3.getComprobarNota());
console.log(alumno4.getComprobarNota());
console.log("----------------------------------");
console.log(escuela.getExpulsarAlumno(alumnos));
console.log("----------------------------------");
escuela.setContratarProfesor([profesor4]);
console.log("----------------------------------");
escuela.setContratarProfesor([profesor2]);
console.log("----------------------------------");
console.log(escuela.getDespedirProfesor(profesores));
