"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var escuela_1 = require("./escuela");
var alumno_1 = require("./alumno");
var profesor_1 = require("./profesor");
var curso_1 = require("./curso");
var alumno1 = new alumno_1.Alumno(123, "Diana", "Ciganda", 30623336);
var alumno2 = new alumno_1.Alumno(321, "Lucas", "Gonzalez", 3984509);
var alumno3 = new alumno_1.Alumno(356, "Elena", "Lopez", 29903423);
var alumno4 = new alumno_1.Alumno(432, "Hector", "Carrera", 33980512);
var alumnos = [alumno1, alumno2, alumno3, alumno4];
var profesor1 = new profesor_1.Profesor(3, "Julio", "Velez", 30982456);
var profesor2 = new profesor_1.Profesor(5, "Sonia", "Garcia", 29907267);
var profesor3 = new profesor_1.Profesor(7, "Emiliano", "Sanchez", 33982001);
var profesores = [profesor1, profesor2, profesor3];
var curso1 = new curso_1.Curso("Artes escenicas", "Expresate con libertad", profesor1, [alumno1, alumno3]);
var curso2 = new curso_1.Curso("Ceramica", "Libera tu ser con el barro", profesor2, [alumno1, alumno2, alumno3, alumno4]);
var curso3 = new curso_1.Curso("Musica", "Clave de sol, el alma al descubierto", profesor3, [alumno1, alumno2, alumno4]);
var escuela = new escuela_1.Escuela([curso1, curso2, curso3], 50);
alumno1.presentacion();
console.log("-----------------------------------------------");
profesor1.presentacion();
console.log("-----------------------------------------------");
curso1.mostrarLista();
console.log("-----------------------------------------------");
escuela.listadoCursos();
